name: Simple CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check file exists
        run: test -f greeting.txt

      - name: Print content
        run: cat greeting.txt
